spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:library_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Tina753546}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=${FLYWAY_ENABLED:false}

app.jwt.secret=${JWT_SECRET:b3f5b1b6f0a4e8d3c9a7f2e6d4b8c1a5e9f3d7b2c6a0e4f8d2b6a1c5e9f3d7b2}

app.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}

app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}

app.admin.default-username=${ADMIN_USERNAME:admin}
app.admin.default-password=${ADMIN_PASSWORD:admin123}

app.storage.book-covers-dir=${BOOK_COVERS_DIR:uploads/book-covers}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB