spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/library_db
spring.datasource.username=postgres
spring.datasource.password=Tina753546

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false

app.jwt.secret=b3f5b1b6f0a4e8d3c9a7f2e6d4b8c1a5e9f3d7b2c6a0e4f8d2b6a1c5e9f3d7b2

app.jwt.expiration-ms=900000

app.jwt.refresh-expiration-ms=604800000

app.admin.default-username=admin
app.admin.default-password=admin123