
CREATE TABLE books (
                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title           VARCHAR(255) NOT NULL,
                       author          VARCHAR(255) NOT NULL,
                       isbn            VARCHAR(255) NOT NULL UNIQUE,
                       publisher       VARCHAR(255),
                       published_year  INTEGER,
                       status          VARCHAR(20)  NOT NULL,
                       created_at      TIMESTAMP    NOT NULL,
                       updated_at      TIMESTAMP    NOT NULL
);

CREATE TABLE members (
                         id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name                VARCHAR(255) NOT NULL,
                         email                    VARCHAR(255) NOT NULL UNIQUE,
                         phone_number             VARCHAR(50),
                         membership_start_date    DATE NOT NULL,
                         membership_expiry_date   DATE NOT NULL,
                         created_at               TIMESTAMP NOT NULL,
                         updated_at               TIMESTAMP NOT NULL
);

CREATE TABLE loans (
                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       book_id      BIGINT NOT NULL REFERENCES books(id),
                       member_id    BIGINT NOT NULL REFERENCES members(id),
                       loan_date    DATE NOT NULL,
                       due_date     DATE NOT NULL,
                       return_date  DATE,
                       status       VARCHAR(20) NOT NULL,
                       created_at   TIMESTAMP NOT NULL,
                       updated_at   TIMESTAMP NOT NULL
);

CREATE INDEX idx_loans_member_id ON loans(member_id);
CREATE INDEX idx_loans_book_id ON loans(book_id);